#!/usr/bin/env bash
cat << EOF
Usage: 
  pm2cd  <pm2_id>  cd到项目目录
  
  pm2reload <pm2_id> 重启并查看标准输出日志

  pm2up <pm2_id> 在项目目录执行svn up

  pm2out <pm2_id> vim查看out日志文件

  pm2error <pm2_id> vim查看error日志文件

  pm2log <pm2_id> <date_pattern> 查看某项目的压缩日志内容

  pm2port 列出pm2启动的node程序都监听了哪些端口

  pm2l [name_pattern] 根据appName模糊查询pm2列表

  pm2id [num] 获取最后num次使用的pm2命令(最后包含pm2_id的命令)

  pm2save [pm2_home_dir]  保存当前pm2进程

  pm2restore [pm2_home_dir]  恢复pm2进程
EOF

grep -q 'alias.*pm2cd=' ~/.bashrc || echo "alias pm2cd='. pm2cd'" >> ~/.bashrc
grep -q 'alias.*pm2cd=' ~/.zshrc || echo "alias pm2cd='. pm2cd'" >> ~/.zshrc

grep -q 'alias.*pm2id=' ~/.bashrc || echo "alias pm2id='. pm2id'" >> ~/.bashrc
grep -q 'alias.*pm2id=' ~/.zshrc || echo "alias pm2id='. pm2id'" >> ~/.zshrc