#!/usr/bin/env bash
if [ -n "$1" ]; then
pm2id=$1
else
echo Usage: $0 pm2_id
exit 1
fi
proj_dir=$(pm2 jlist | JSON.sh | grep -P '^\[\d+\].*pm_id":'$pm2id',' |  grep -Po 'pm_cwd":"\K.*?(?=")')
echo $proj_dir
builtin cd $proj_dir;
