#!/usr/bin/env bash
if [ -n "$1" -a -n "$2" ]; then
pm2id=$1
filename_pattern=$2
else
echo "Usage: $0 <pm2_id> <date_pattern>"
exit 1
fi
content_pattern=$3
logfile_prefix=$(pm2 info 2  | grep -Po 'out log path.*?│ \K.*(?=\b)')
logfile_prefix=${logfile_prefix%.log}
zgrep '' `ls $logfile_prefix*${filename_pattern}*.gz`
