#!/usr/bin/env bash

PM2_HOME=${PM2_HOME:-~/.pm2}
[ -d "$1" ] && PM2_HOME=$1

[ -d "$PM2_HOME" ] || {
  echo "Usage: $0 <pm2_home_dir>"
  exit 1;
}

[ -e "$PM2_HOME/dump.pm2.bak" ] || {
  echo "$PM2_HOME/dump.pm2.bak文件不存在"
  exit 1;
}

cp  $PM2_HOME/dump.pm2.bak $PM2_HOME/dump.pm2
echo "执行：pm2 resurrect 恢复pm2进程"